apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: go-foo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: go-foo
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/araminian/kargo-demo
          checkout:
          - branch: main
            path: ./main
          - branch: gitops
            path: ./gitops
      - uses: git-clear
        config:
          path: ./gitops/stage
      - uses: helm-update-image
        as: update-image
        config:
          path: ./main/services/foo/ci/deployment-values/stage.yaml
          images:
          - image: rminz/go-app-foo
            key: image.tag
            value: Tag
      - uses: helm-template 
        config:
          path: ./main/ci/charts/app
          valuesFiles:
            - ./main/services/foo/ci/deployment-values/stage.yaml
            - ./main/ci/charts/app/values.yaml
          outputPath: ./gitops/stage/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./gitops/stage
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./gitops/stage
          targetBranch: gitops
      - uses: argocd-update
        config:
          apps:
          - name: go-foo-stage
            sources:
            - repoURL: https://github.com/araminian/kargo-demo
              desiredCommitFromStep: commit