apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: go-foo
spec:
  verification:
    analysisTemplates:
    - name: go-foo-prod-test
  requestedFreight:
  - origin:
      kind: Warehouse
      name: go-foo
    sources:
      stages:
        - stage
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/araminian/kargo-demo
          checkout:
          - branch: main
            path: ./main
          - branch: gitops
            path: ./gitops
      - uses: git-clear
        config:
          path: ./gitops/prod
      - uses: helm-update-image
        as: update-image
        config:
          path:  ./main/ci/charts/app/values.yaml
          images:
          - image: rminz/go-app-foo
            fromOrigin:
              kind: Warehouse
              name: go-foo
            key: image.tag
            value: Tag
      - uses: helm-template 
        config:
          path: ./main/ci/charts/app
          releaseName: go-foo-prod
          namespace: go-foo-prod
          valuesFiles:
            - ./main/services/foo/ci/deployment-values/prod.yaml
            - ./main/ci/charts/app/values.yaml
          outPath: ./gitops/prod/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./gitops/prod
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./gitops/prod
          targetBranch: gitops
      - uses: argocd-update
        config:
          apps:
          - name: go-foo-prod
            sources:
            - repoURL: https://github.com/araminian/kargo-demo
              desiredCommitFromStep: commit