apiVersion: v1
kind: Pod
metadata:
  name: checker
  labels:
    name: checker
spec:
  containers:
  - name: checker
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
